name: Rangos
version: 1.0
main: com.Rangos.Rangos
api-version: 1.20
description: Sistema de rangos automáticos con tiempo jugado
author: Enrique Cazun
commands:
  tiempo:
    description: Muestra tu tiempo jugado y rango actual
    usage: /tiempo